export const CONSTANTS = {
    SPLASH_SCREEN_HIDE_REQUEST: 'SPLASH_SCREEN_HIDE_REQUEST',
    SPLASH_SCREEN_HIDE_SUCCESS: 'SPLASH_SCREEN_HIDE_SUCCESS',
    SPLASH_SCREEN_HIDE_FAILURE: 'SPLASH_SCREEN_HIDE_FAILURE',

    RECORD_SAVE_REQUEST: 'RECORD_SAVE_REQUEST',
    RECORD_SAVE_SUCCESS: 'RECORD_SAVE_SUCCESS',
    RECORD_SAVE_FAILURE: 'RECORD_SAVE_FAILURE',

    RECORD_GET_REQUEST: 'RECORD_GET_REQUEST',
    RECORD_GET_SUCCESS: 'RECORD_GET_SUCCESS',
    RECORD_GET_FAILURE: 'RECORD_GET_FAILURE',

    RECORD_DELETE_REQUEST: 'RECORD_DELETE_REQUEST',
    RECORD_DELETE_SUCCESS: 'RECORD_DELETE_SUCCESS',
    RECORD_DELETE_FAILURE: 'RECORD_DELETE_FAILURE',

}